version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
#    setup_py_install: true


sphinx:
  configuration: docs/conf.py

python:
   install:
     - requirements: docs/rtd-requirements.txt

# needed to get swig to install
#conda:
#  environment: docs/rtd-condalist.yml
