name: oapackage
channels:
- conda-forge
- defaults
dependencies:
- python=3.5 # rtd python version
- numpy
- pip
- swig
- matplotlib
- pip:
  - scanf
  
# conda env create --name oapackage -f condalist.yml