import oapackage.conference
import oapackage.Doptim
import oapackage.oahelper
from oapackage.Doptim import (  # noqa
    Doptimize,
    array2Dtable,
    calcScore,
    filterPareto,
    generateDscatter,
    optimDeffPython,
    scoreDn,
    selectDn,
)
from oapackage.oahelper import (  # noqa
    DefficiencyBound,
    array2html,
    array2latex,
    arrayfile_generator,
    checkArrayFile,
    checkFiles,
    checkFilesOA,
    checkOAfile,
    choose,
    compressOAfile,
    create_pareto_element,
    createPareto,
    deprecated,
    designStandardError,
    enlargelims,
    extendSingleArray,
    fac,
    fileinput,
    finddirectories,
    findfiles,
    findfilesR,
    floatformat,
    formatC,
    getArrayFile,
    guitest_monitorSizes,
    gwlp2str,
    helmert_contrasts,
    isstr,
    joinArrayLists,
    jseq,
    makearraylink,
    mkdirc,
    monitorSizes,
    nArrayFile,
    niceplot,
    oainfo,
    oaIsBinary,
    oalib,
    parseProcessingTime,
    plot2Dline,
    randomizearrayfile,
    runcommand,
    runExtend,
    safemax,
    safemin,
    selectArrays,
    selectArraysInFile,
    selectJ,
    selectParetoArrays,
    series2htmlstr,
    setWindowRectangle,
    sortcols,
    sortrows,
    static_var,
    strftime,
    test_selectJ,
    tilefigs,
    timeString,
    tprint,
    webbrowser,
    write_text_arrayfile,
)

""" Orthogonal Array package

The Orthogonal Array package is a package to generate and analyse orthogonal
arrays, optimal designs and conference matrices. For more information see

http://github.com/eendebakpt/oapackage

"""
# from oalib import *  # noqa # legacy structure
from oalib import (  # noqa
    ParetoDoubleLong,
    array_link,
    arraydata_t,
    arrayfile_t,
    arraylink2arraydata,
    exampleArray,
    reduceGraphNauty,
    reduceOAnauty,
    transformGraphMatrix,
    OAextend,
    jstructconference_t,
    conference2DSD,
    Jcharacteristics_conference,
    compareLMC,
    LMCcheckOriginal,
    generateConferenceExtensions,
    reduceLMCform,
    array2modelmatrix,
    update_array_link,
    writearrayfile,
    readarrayfile,
    create_array_link,
    ABINARY,
    ATEXT,
    GWLPmixed,
    splitTag,
    is_root_form,
    rankStructure,
    GWLP,
    projDeff,
    print_column,
    mvalue_t_double,
    get_time_ms,
    mycheck_handler,
    distance_distribution_shape,
    splitFile,
    PECsequence,
    projectionDOFvalues,
    mvalue_t_long,
    throw_runtime_exception,
    distance_distribution_mixed,
    macwilliams_transform,
    PICsequence,
    symmetry_group,
    array2eigenModelMatrixMixed,
    ndarray_double,
    array_transformation_t,
    krawtchouk,
    double_conference_foldover_permutation,
    reductionDOP,
    LMC_MORE,
    LMC_LESS,
    LMC_EQUAL,
    macwilliams_transform_mixed,
    distance_distribution_mixed_inplace,
    conference_t,
    arraylist_t,
    array2modelmatrix_sizes,
    reduceDOPform,
    LMCcheck,
    compareJ54,
    conference_design2modelmatrix,
    splitDir,
    extend_conference_restricted,
    arrayrankInfo,
    isConferenceFoldover,
    LMCreduction_t,
    distance_distribution,
    ALATEX,
)

oapackage.oalib.setloglevel(oapackage.oalib.SYSTEM)
oapackage.oalib.log_print(-oapackage.oalib.SYSTEM, "")
__version__ = oapackage.oalib.version()

__description__ = "Orthogonal Array package"
__uri__ = "http://www.pietereendebak.nl/oapackage/index.html"
